# Generated by Django 3.2.25 on 2024-07-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='../sample_dsxclr6km.png', upload_to='images/'),
        ),
    ]
