# Generated by Django 5.0.7 on 2024-07-19 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_profile_image_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='creator',
            new_name='owner',
        ),
    ]
