# Generated by Django 5.0.7 on 2024-07-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_creator_profile_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='owner',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='profile_banner',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='../dinner.219fa9d437e9', upload_to='images/'),
        ),
    ]
