# Generated by Django 5.0.7 on 2024-07-26 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('build_name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('main_image', models.ImageField(default='../default_build_nvxeo7', upload_to='images/')),
                ('gallery_image_1', models.ImageField(default='../default002_r4me0b', upload_to='images/')),
                ('gallery_image_2', models.ImageField(default='../default001_p368vd', upload_to='images/')),
                ('gallery_image_3', models.ImageField(default='../default003_zdfw1y', upload_to='images/')),
                ('gallery_image_4', models.ImageField(default='../default005_p3syzs', upload_to='images/')),
                ('build_cpu', models.CharField(max_length=255)),
                ('build_mobo', models.CharField(max_length=255)),
                ('build_ram', models.CharField(max_length=255)),
                ('build_disk', models.CharField(max_length=255)),
                ('build_gpu', models.CharField(max_length=255)),
                ('build_case', models.CharField(max_length=255)),
                ('build_monitor', models.CharField(max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_rating_1', models.ManyToManyField(blank=True, editable=False, related_name='user_rating_1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
